name: Maven CI/CD (Lab)

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package

    - name: Deploy WAR to Tomcat (Lab)
      run: |
        echo "Deploying WAR to Tomcat in Lab..."
        curl -T target/insured-assurance.war \
          -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASS }} \
          "https://${{ secrets.TOMCAT_HOST }}:${{ secrets.TOMCAT_PORT }}/manager/text/deploy?path=/insured-assurance&update=true"
